# ex28.py  布尔表达式练习
print("2True:",True and True)
print("3False:", False and True)
print("4False:", 1 ==1 and 2 ==1 )
print("5True:", "test" == "test")
print("6True:", 1 == 1 or 2 != 1)
print("7True:", True and 1 ==1 )
print("8False:", False and 0 != 0)
print("9True:", True and 1 ==1 )
print("10False:", "test" == "testing")
print("11False:", 1 != 0 and 2 ==1)
print("12True:", "test" != "testing")
print("13False:", "test" == 1)
print("14True:", not (True and False))
print("15False:", not (1 ==1 and 0 != 1))
print ("16False:", not (10 ==1  or 1000 == 1000))
print ("17False:", not ( 1 != 10 or 3 ==4))
print("18True: ",  not ("testing" == "testing" and "zed" == "cool Guy"))
print("19True:", 1 ==1 and not ("testing" ==1 or 1 ==0))
print("20False:", "chunky" == "bacon" and not (3==4 or 3 ==3))
print("21False:", 3 ==3 and not ("testing" == "testing" or "Python" == "Fun"))